# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banks.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'banks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\x12\x04\x62\x61nk\"7\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tinterface\x18\x02 \x01(\t\x12\r\n\x05money\x18\x03 \x01(\x05\"+\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x32\xa4\x01\n\x0b\x42\x61nkService\x12,\n\x0bMsgDelivery\x12\r.bank.Request\x1a\x0e.bank.Response\x12\x32\n\x11Propagate_Deposit\x12\r.bank.Request\x1a\x0e.bank.Response\x12\x33\n\x12Propagate_Withdraw\x12\r.bank.Request\x1a\x0e.bank.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=21
  _globals['_REQUEST']._serialized_end=76
  _globals['_RESPONSE']._serialized_start=78
  _globals['_RESPONSE']._serialized_end=121
  _globals['_BANKSERVICE']._serialized_start=124
  _globals['_BANKSERVICE']._serialized_end=288
# @@protoc_insertion_point(module_scope)
